#!/usr/bin/python3
def roman_to_int(roman_string):
    result = 0
    if roman_string is None or type(roman_string) != str:
        return 0
    romans = {'I': 1, 'V': 5, 'X': 10, 'L': 50, 'C': 100, 'D': 500, 'M': 1000}
    num_len = len(roman_string)

    if num_len == 1:
        new = [x for x in romans if roman_string[0] in x]
        print("este " + new[0])
        #result += new[0][0]
        return result

    for num in range(num_len - 1):
        new = [x for x in romans if roman_string[num] in x][0]
       # print("pasa")
        
    
    """
    for i in range(num_len - 1):
        for j in range(len(romans)):
            if roman_string[i] == romans[j][0]:
                if roman_string[i] == "I":
                    if roman_string[i + 1] != "I":
                        new = [x for x in romans if roman_string[i+1] in x][0]
                        result += new[1]
                        result -= 1
                    else:
                        result += 2
                else:
                    result += romans[j][1]
          """
    return result
